INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G000', 'G000000', '관리자', 'ROLE_ADMIN');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G000', 'G000001', '사용자', 'ROLE_USER');

INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001000', '수온 임계치 이상', '수온 임계치 이상');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001001', '용존산소 임계치 이상', '용존산소 임계치 이상');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001002', 'PH 임계치 이상', 'PH 임계치 이상');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001003', '선회 임계치 이상', '선회 임계치 이상');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001004', '입올림 임계치 이상', '입올림 임계치 이상');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001005', '흑화 임계치 이상', '흑화 임계치 이상');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001006', '폐사 발생', '폐사 발생');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G001', 'G001007', '탈장 및 출혈 발생', '탈장 및 출혈 발생');

INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G002', 'G002000', '수질센서', '수질센서');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G002', 'G002001', 'CCTV', 'CCTV');

INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G003', 'G003000', '선회', '선회');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G003', 'G003001', '입올림', '입올림');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G003', 'G003002', '흑화', '흑화');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G003', 'G003003', '폐사', '폐사');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G003', 'G003004', '탈장 및 출혈', '탈장 및 출혈');
INSERT INTO CODE_INFO_TB (UP_CODE_ID, G_CODE_ID, CODE_ID, CODE_NM, CODE_VALUE) VALUES ( null, 'G003', 'G003005', '선회 입올림', '선회 입올림');

COMMIT;
